$("#login").click(function(){
    $("#pageload").load("http://localhost:8000/login.html");
});
$("#register").click(function(){
    $("#pageload").load("http://localhost:8000/registered.html");
});
$("#contact").click(function(){
    $("#pageload").load("http://localhost:8000/contact.html");
});
